services: 
  mariadb: 
    image: mariadb
    container_name: taller2
    restart: unless-stopped
    environment: 
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MARIADB_DATABASE: "${DB_NAME}" 
      MARIADB_USER: "${DB_USER}" 
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    ports: 
      - "${DB_PORT}:3306"
    volumes: 
      - mariadb_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
volumes: 
    mariadb_data: